name: blocs
description: A new Flutter package project.
version: 0.0.1
homepage: "https://example.com"
publish_to: "none"
environment:
  sdk: ">=2.17.3 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  bloc:
  equatable:
  flutter:
    sdk: flutter
  flutter_bloc:
  rxdart:
  #
  models:
    path: ../models

  request:
    path: ../request
    #
  stream_transform:
  meta:
  bloc_concurrency:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
