name: request
description: A new Flutter package project.
version: 0.0.1
homepage: "https://example.com"
publish_to: "none"
environment:
  sdk: ">=2.17.3 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    
    sdk: flutter

  dio:

  # Personl packages
  models:
    path: ../models


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
